---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tumbo-server
  namespace: tumbo-dev
spec:
  selector:
    matchLabels:
      app: tumbo-server
  replicas: 2
  template:
    metadata:
      labels:
        app: tumbo-server
    spec:
      containers:
      - name: tumbo-server
        image: philipsahli/go-tumbo:latest
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: tumbo-config-volume
            mountPath: /etc/tumbo
      volumes:
        - name: tumbo-config-volume
          configMap:
            name: tumbo-config

