POST https://dev.tumbo.io/auth
Content-Type: application/x-www-form-urlencoded

username=admin&password=mysecretpassword

###
GET http://localhost:8000/api/v1/projects?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjIxMjMyZjI5N2E1N2E1YTc0Mzg5NGEwZTRhODAxZmMzIiwicGFzc3dvcmQiOiI0Y2FiMmEyZGI2YTNjMzFiMDFkODA0ZGVmMjgyNzZlNiIsImV4cCI6MTYwMjU5MzI2MiwiaXNzIjoiZ2luLWJsb2cifQ.YS9rRUvEU-BaCP5HPYQ71iDvj5uuPEqAxrLXBfSSLJw

###

