---
platform: linux

inputs:
  - name: go-tumbo-git
params:
  GO111MODULE: "on"

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: 1.14-stretch

run:
  path: /bin/sh
  args:
    - -c
    - |
      set -e
      cd go-tumbo-git

      cd integrationtests
      go test -v ./...
      echo $?
