---
platform: linux

inputs:
  - name: go-tumbo-git
params:
  GO111MODULE: "on"

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: 1.15-buster

run:
  path: /bin/sh
  args:
    - -c
    - |
      set -e
      cd go-tumbo-git
      # vet only pkg becaues the failing examples makes it fail
      go vet ./...
      go test -v ./...
      echo $?
