---
resources:
  - name: go-tumbo-git
    type: git
    icon: github
    source:
      uri: https://github.com/sahlinet/go-tumbo3.git

  - name: golang-1.14.x-image
    type: registry-image
    icon: docker
    source:
      repository: golang
      tag: 1.14-stretch

  - name: elm-image
    type: registry-image
    icon: docker
    source:
      repository: codesimple/elm
      tag: 0.19

  - name: go-tumbo-image
    type: registry-image
    icon: docker
    source:
      repository: philipsahli/go-tumbo
      username: ((docker.username))
      password: ((docker.password))

task-config: &task-config
  platform: linux
  inputs:
    - name: go-tumbo-git
  params:
    GO111MODULE: "on"
  run:
    path: /bin/sh
    args:
      - -c
      - |
        set -e
        cd go/go-tumbo3

        go vet ./...
        go test -v ./...

jobs:
  - name: unittest
    public: true
    plan:
      - get: go-tumbo-git
        trigger: true
      - get: golang-1.14.x-image
      - task: run-tests
        image: golang-1.14.x-image
        config:
          <<: *task-config
          run:
            path: /bin/sh
            args:
              - -c
              - |
                set -e 
                cd go-tumbo-git
                go vet ./...
                go test -v ./...
                echo $?
  - name: web
    public: true
    plan:
      - in_parallel:
          - get: go-tumbo-git
            trigger: true
          - get: elm-image
      - task: make-elm
        image: elm-image
        config:
          platform: linux
          inputs:
            - name: go-tumbo-git
              path: go-tumbo-git
          run:
            path: /bin/sh
            args:
              - -c
              - |
                set -e
                cd go-tumbo-git/web/elm
                elm make src/Main.elm --output ../static/app.js

  - name: build-and-push
    plan:
      - get: go-tumbo-git
        passed: ["web", "unittest"]
        trigger: true
      - get: golang-1.14.x-image
      - task: build-binary
        image: golang-1.14.x-image

        config:
          <<: *task-config
          run:
            path: /bin/sh
            args:
              - -c
              - |
                set -e
                export CGO_ENABLED=0
                cp -rp go-tumbo-git go-tumbo-git-updated
                cd go-tumbo-git-updated/go-tumbo-git

                go get github.com/GeertJohan/go.rice
                go get github.com/GeertJohan/go.rice/rice

                go generate ./...
                go build -o build/tumbo ./cmd/tumbo
          outputs:
            - name: go-tumbo-git-updated
      # - task: output
      #   image: golang-1.14.x-image
      #   config:
      #     << : *task-config
      #     run:
      #       path: /bin/sh
      #       args:
      #         - -c
      #         - |
      #            pwd
      #            ls -alR
      #     inputs:
      #     - name: go-tumbo-git-updated
      - task: build-image
        privileged: true
        config:
          platform: linux

          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task

          inputs:
            - name: go-tumbo-git-updated

          params:
            CONTEXT: go-tumbo-git-updated/go-tumbo-git/build/

          outputs:
            - name: image

          run:
            path: build

      # push using `registry-image` resource
      - put: go-tumbo-image
        params: { image: image/image.tar }
