---
resource_types:
  - name: pull-request
    type: registry-image
    source: { repository: teliaoss/github-pr-resource }

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: go-tumbo3-master
    type: git
    icon: github
    source:
      uri: https://github.com/concourse/concourse

  - name: go-tumbo3-pr
    type: pull-request
    icon: source-pull
    source:
      repository: sahlinet/go-tumbo3
      access_token: ((github-access.token))

  #  - name: golang-1.14.x-image
  #    type: registry-image
  #    icon: docker
  #    source:
  #      repository: golang
  #      tag: 1.14-stretch

  - name: notify
    type: slack-notification
    source:
      url: ((slack-webhook.webhook))

jobs:
  - name: unit
    public: true
    max_in_flight: 3
    on_failure:
      put: go-tumbo3-pr
      inputs: [go-tumbo3-pr]
      params: { path: go-tumbo3-pr, status: failure, context: unit }

      get_params: { skip_download: true }
    on_success:
      put: go-tumbo3-pr
      inputs: [go-tumbo3-pr]
      params: { path: go-tumbo3-pr, status: success, context: unit }
      get_params: { skip_download: true }
    plan:
      - in_parallel:
          - get: go-tumbo3-pr
            trigger: true
            version: every
          - get: go-tumbo3-master
      #          - get: golang-1.14.x-image
      - put: concourse-status-update-pending
        resource: go-tumbo3-pr
        inputs: [go-tumbo3-pr]
        params: { path: go-tumbo3-pr, status: pending, context: unit }
        get_params: { list_changed_files: true, skip_download: true }

      - task: go-unittests
        file: go-tumbo3-pr/ci/tasks/unittest.yaml
        input_mapping:
          go-tumbo-git: go-tumbo3-pr
        on_failure:
          put: notify
          params:
            text: |
              The pipeline $BUILD_PIPELINE_NAME has failed, check:
              $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        on_success:
          put: notify
          params:
            text: |
              The pipeline $BUILD_PIPELINE_NAME has succeeded, check:
              $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

      - task: build-elm
        file: go-tumbo3-pr/ci/tasks/web-build.yaml
        input_mapping:
          go-tumbo-git: go-tumbo3-pr
        on_failure:
          put: notify
          params:
            text: |
              The pipeline $BUILD_PIPELINE_NAME has failed, check:
              $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        on_success:
          put: notify
          params:
            text: |
              The pipeline $BUILD_PIPELINE_NAME has succeeded, check:
              $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
